### ISSUE TITLE
Camera isn't working after updating to v1.5.2-alpha

### ISSUE THREAD

**Issue by bearpawmaxim** [sca075/valetudo_vacuum_camera#57]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I'm using Valetudo Vacuum Camera with Xiaomi Lovelace Vacuum Map card.
After updating the integration to v1.5.2-alpha the camera stopped to update: it just shows stale image all the time.

### What version of an integration has described problem?

v1.5.2-alpha

### What was the last working version of an integration?

v1.5.1

### What vacuum model do you have problems with?

Roborock S7

### Please firmware installed on your Vacuum.

2023.10.0

### What version of Home Assistant do you use?

core-2023.12.3

### What type of installation are you running?

Home Assistant Supervised

### Camera's settings.

```yaml
idk where to get it from...
```

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
2023-12-18 11:49:54.763 WARNING (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.image_handler] rosha: Error in get_image_from_json: 'NoneType' object has no attribute 'items'
```

**Comment by sca075** [comment]
Thanks @bearpawmaxim will check it out soon..

**Comment by bearpawmaxim** [comment]
> Thanks @bearpawmaxim will check it out soon..

Updated the issue: added missing problem description.. Sorry

**Comment by sca075** [comment]
> > Thanks @bearpawmaxim will check it out soon..
> 
> 
> 
> Updated the issue: added missing problem description.. Sorry

@bearpawmaxim I think to know where is the problem ;) 
I'm currently busy at work.. so I didn't check yet but apparently it is because it failed to load the rooms. I would need few hours to complete the troubleshooting. 
If you don't mind to roll back to v1.5.1 for a while.. I would release the 1.5.2 final as soon I can convert back to Hyper the S5 I use.. will also improve the trace logs so that we will get the line where it stops.. I'm sorry as I had to set the alpha as a pre-release..

**Comment by bearpawmaxim** [comment]
@sca075 thanks!
Already reverted to v1.5.1, so everyhting is fine for me

**Comment by duffmiester** [comment]
Just fyi i had the same issue and had to revert back

**Comment by sca075** [comment]
@duffmiester and @bearpawmaxim,
I've been aboard for work in the last week and I couldn't yet work on it yet but soon I hope to fix it. As soon I can verify it on the S5 that currently runs with RE firmware (and there I didn't get this error) I will post the final release for 1.5.2 and hopefully close this issue once per all.
Thanks guys for testing the "alpha" version (that once again I had to set as a pre-release instead of final). I wish you a great Xmas time with your Families and all the best for the new coming year.
Regards,
Sandro

**Comment by sca075** [comment]
Released the v1.5.2 that fix the above issue. Tested with both firmwares, the new function is now fully released
